export enum Ascension {
  None = 'NONE',
  Elite = 'ELITE',
  ElitePlus = 'ELITE_PLUS',
  Legendary = 'LEGENDARY',
  LegendaryPlus = 'LEGENDARY_PLUS',
  Mythic = 'MYTHIC',
  MythicPlus = 'MYTHIC_PLUS',
  Ascended = 'ASCENDED',
  Ascended1Star = 'ASCENDED_1_STAR',
  Ascended2Star = 'ASCENDED_2_STAR',
  Ascended3Star = 'ASCENDED_3_STAR',
  Ascended4Star = 'ASCENDED_4_STAR',
  Ascended5Star = 'ASCENDED_5_STAR',
}
